### ISSUE TITLE
Show blank

### ISSUE THREAD

**Issue by tangyi90** [dcblogdev/simple-cms#1]
`<?php
require('../config.php'); 
//include the class
include('../includes/paginator.php');

//创建新的对象传递的页数和标识符
$pages = new Paginator('10','p');

//获得总记录数
$stmt = $db->prepare('SELECT id FROM news');
$stmt->execute();
$rows = $stmt->fetch();

$total = count($rows);

//传递记录数
$pages->set_total($total); 

$stmt = $db->prepare('SELECT * FROM news '.$pages->get_limit());
$stmt->execute();
$data = $stmt->fetch();

foreach($data as $row) {
    //在这里显示记录
}

//创建页面链接
echo $pages->page_links();

 ?>`

Show blank

Are there any mistakes with me?

**Comment by dcblogdev** [comment]
this project does not use pdo but the obsolete mysql functions, there is no $db setup at all. This is from 3 years ago I recommend using PDO instead. You can set that up in your config class

like this:

```php
//database credentials
define('DBHOST','localhost');
define('DBUSER','username');
define('DBPASS','password');
define('DBNAME','database name');

$db = new PDO("mysql:host=".DBHOST.";dbname=".DBNAME, DBUSER, DBPASS);
```
